name: Gatsby Publish

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      
      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install Python
        run: uv python install 2.7
      
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.SECRET_TOKEN }}
          deploy-branch: master
