name: Gatsby Publish

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18
    
      - name: Setup Python 2
        run: |
          sudo apt install build-essential zlib1g-dev libssl-dev libreadline-dev libncurses5-dev libsqlite3-dev tk-dev libgdbm-dev -y
          wget https://www.python.org/ftp/python/2.7.9/Python-2.7.9.tgz
          sudo tar xzf Python-2.7.9.tgz
          cd Python-2.7.9
          sudo ./configure --enable-optimizations
          sudo make altinstall
          python2.7 -V
          sudo ln -sfn '/usr/local/bin/python2.7' '/usr/bin/python2'
          sudo update-alternatives --install /usr/bin/python python /usr/bin/python2 1
      
      - name: Install dependencies
        run: npm install
      
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.SECRET_TOKEN }}
          deploy-branch: master
